const String SIGN_IN = "Sign In";
const String LOGOUT = "Logout";
const String ADD_NEW_ALERT = "Add New Alert";
const String SAVED_ALERTS = "Saved Alerts";
const String SETTINGS = "Settings";
const String RECORDINGS_FOLDER_NAME = "Vibe Recordings";
const String NEW_RECORDING_NAME = " - New Recording";
const String CANCEL = "Cancel";
const String SAVE = "Save";
